### ISSUE TITLE
Copy from template issues

### ISSUE THREAD

**Issue by broderickhyman** [dojohnso/OctoPrint-SpoolManager#11]
See issue in [OllisGit repo](https://github.com/OllisGit/OctoPrint-SpoolManager/issues/335).

@dojohnso I can look into this issue tonight. Do you have any thoughts on a communication platform for discussing priorities and dividing work? Or should we just use GitHub?

**Comment by dojohnso** [comment]
thanks for bringing this over. I'd like to get as many as possible listed here so work can actually be done on this plugin. i won't have a ton of time to do much, at least to start. I'll be able to manage the merges and releases and such though, no problem. let's stick to github for now, feel free to grab whatever from the other repo and bring over here and submit changes. maybe if there becomes enough i'll start up a project on here or something.

**Comment by dojohnso** [comment]
resolves with https://github.com/dojohnso/OctoPrint-SpoolManager/pull/13 - will use this as a 1.7.3 release.
