### ISSUE TITLE
No button to add new spools

### ISSUE THREAD

**Issue by hobbieman** [dojohnso/OctoPrint-SpoolManager#12]
I installed via:

~/OctoPrint/venv/bin/pip install https://github.com/dojohnso/OctoPrint-SpoolManager/releases/latest/download/main.zip

I am unable to add any spools as I don't see a button anywhere to do so.  I also tried this with 3 different browsers (chrome, edge and safari) but no difference.

![spoolmgr issue](https://github.com/dojohnso/OctoPrint-SpoolManager/assets/49247428/770e9acd-36d5-498c-8958-9a036a782693)

**Comment by hobbieman** [comment]
BTW, I tried this with 3 different web browsers (chrome, safari and edge)... same results

**Comment by broderickhyman** [comment]
@hobbieman The spools are added and managed via a Spools tab in the main window
![image](https://github.com/dojohnso/OctoPrint-SpoolManager/assets/2431259/dc90363f-9cfb-4ef8-a86d-62c73023fbd3)

**Comment by hobbieman** [comment]
Doh! Thank you!
