### ISSUE TITLE
Bug - When using Consolidate Temp Control plugin

### ISSUE THREAD

**Issue by OnceWasPerfect** [dojohnso/OctoPrint-SpoolManager#19]
Not sure if its with SpoolManager or the Consolidate Temp Control plugin but if the Consolidate Temp Control plugin is set to horizontal the Spool management window gets sized wrong.  If I set it to vertical Spool management goes back to normal.
![image](https://github.com/dojohnso/OctoPrint-SpoolManager/assets/53492647/1d84821a-9fe7-4d08-9d74-d539fab29fac)

**Comment by dojohnso** [comment]
we can take a look at some point. likely a little bit of both, but we should be able to find a way to accommodate for that. 

i noticed some... odd choices with the UI on the printjobhistory plugin, similar stuff here. I'm hoping to give both a little refresh at some point.

**Comment by OnceWasPerfect** [comment]
Awesome, thanks for taking up the project!
