### ISSUE TITLE
German language

### ISSUE THREAD

**Issue by TMTYD** [dojohnso/OctoPrint-SpoolManager#27]
Hi

What would be nice if the Spool Manager were also available in German, e.g. I don't know what enclosure means.

**Comment by Hottabych-** [comment]
Enclosure is 'Gehäuse' in German e.g. as you can see one here https://www.prusa3d.com/de/produkt/original-prusa-enclosure-3/ 
@dojohnso If interested I am willing to help for translation. But my skills are not in using 'github' ;-) if I can have a file with the English text then it's perfect for me.

**Comment by TMTYD** [comment]
thx

**Comment by Hottabych-** [comment]
:-)

**Comment by Jadefunkel** [comment]
One more volunteer for the german translation here.
As soon there is a translation file I could check :-)
