### ISSUE TITLE
[Bug] No Spool Selected (former issue #33, but this was never resolved.)

### ISSUE THREAD

**Issue by Jartoos** [dojohnso/OctoPrint-SpoolManager#57]
I still have this issue, I was never able to use the spool manager plugin because of it.
![image](https://github.com/user-attachments/assets/1cda98e5-41f3-476e-bb96-1374c26847c4)

I wil try installing the PrintTimeGenious plugin to see if this resolves the issue.

**Comment by WildRikku** [comment]
Could you give more information on when this issue occured? I often have it when I upload a Gcode file and immediately click "load & print". The reason is that Octoprint needs some time (sometimes 10 seconds or more) to process the Gcode internally and as long as it is not done, SpoolManager can't calculate the filament amount.

**Comment by Jartoos** [comment]
> Could you give more information on when this issue occured? I often have it when I upload a Gcode file and immediately click "load & print". The reason is that Octoprint needs some time (sometimes 10 seconds or more) to process the Gcode internally and as long as it is not done, SpoolManager can't calculate the filament amount.

The issue is solved for me.
I found in another thread that you could solve this issue by installing the following plugin first : 
"PrintTimeGenius Plugin"
As soon as I had this plugin installed, the Spoolmanager worked without further issue.

**Comment by Jartoos** [comment]
The issue is solved for me.
I found in another thread that you could solve this issue by installing the following plugin first : 
"PrintTimeGenius Plugin"
As soon as I had this plugin installed, the Spoolmanager worked without further issue.
